In [1]:
import numpy as np


In [4]:
#method 1 simple array
v = np.array([1,2,3])
print(v)

[1 2 3]


In [5]:
#method 2 2d array
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [8]:
#method 3 2d array
v2 = np.arange(24).reshape(2,3,4) 
print(v2)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [13]:
#method 4 size of items
v3 = np.array([(1,2,3)])
print(v3.itemsize)

4


In [14]:
#method 5 slicing
v4=np.array([(3,2,3,4),(3,4,5,6)])
print(v4[0:,3])

[4 6]


In [15]:
#method 6 sum of array 
#slicing
v5=np.array([(1,2,3,4),(3,5,6,6)])
print(v5[0:,2])

[3 6]


In [16]:
#method 7 square root
v6=np.array([(4,2,3),(7,2,5,)])
print(np.sqrt(v6))

[[2.         1.41421356 1.73205081]
 [2.64575131 1.41421356 2.23606798]]


In [18]:
#method 8 generate any random number array
print(np.random.rand(6, 2))

[[0.22039869 0.3320378 ]
 [0.4514811  0.46062351]
 [0.29900983 0.00737139]
 [0.43643    0.15304231]
 [0.04124746 0.91606369]
 [0.35327395 0.91484435]]


In [19]:
#method 9 arrange
B = np.arange(3)
C = np.array([2., -1., 4.])
np.add(B, C)

array([2., 0., 6.])

In [23]:
#method 10 arrange with **3
v8 = np.arange(10)**3
v8

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [24]:
#method 11
v9 = np.arange(10)**3
a[ : :-1] 

array([[1, 2, 3]])

In [28]:
#method 12 function in np
 
def function(x,y):
    return 4*x+y

c = np.fromfunction(f,(5,4),dtype=int)
for element in c.flat:
    print(element)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


In [126]:
#method 13 zero array

import numpy as np
arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [127]:
#method 14
null_vector =np.zeros(8)
null_vector

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [128]:
#method 15
values = np.array(range(30,50))
values

array([30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46,
       47, 48, 49])

In [129]:
#method 16
identity_mat = np.identity(5)
identity_mat

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [130]:
#method 17 multiple array
arr1 = np.array([[1., 4., 9.],[4., 7., 6.]])  
arr2 = np.array([[0., 3., 1.],[7., 3., 12.]])
arr1 * arr2

array([[ 0., 12.,  9.],
       [28., 21., 72.]])

In [131]:
#method 18 ones 
arr = np.ones((4,4))
arr[1:3,1:3]=0
arr

array([[1., 1., 1., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 1., 1., 1.]])

In [132]:
#method 19 random 5 by 5 array

arr =np.random.randn(5,5)
np.min(arr), np.max(arr)

(-1.4548119453283646, 2.1028272248937276)

In [133]:
#method 20 identify digonal array
print(np.identity(6))

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [134]:
#method 21
print(np.diag(np.arange(0, 18, 6)))

[[ 0  0  0]
 [ 0  6  0]
 [ 0  0 12]]


In [135]:
#method 22 append arrays 
arr1 = np.array([[1, 4, 3], [5, 5, 6]])
arr2 = np.array([[7, 9, 7], [4, 19, 12]])
arr = np.append(arr1, arr2, axis=1)
print(arr)

[[ 1  4  3  7  9  7]
 [ 5  5  6  4 19 12]]


In [136]:
#method 23 power array
print(np.power(arr1, arr2))

[[          1      262144        2187]
 [        625  -463433411 -2118184960]]


In [137]:
#method 24 sorting array
v11 = np.array([[1,4],[3,1]])
np.sort(v11)

array([[1, 4],
       [1, 3]])

In [55]:
#method 25
v12 = np.array([[5, 9, 6, 0],
              [6, 3, 7, 22]])
np.ptp(v12, axis=1)

array([ 9, 19])

In [61]:
#method 26 max
v13 = np.array([1,2,3,4,7,9])
print(v13.max())

9


In [64]:
#method 27 min
a = np.array([1,2,0,3])
print(a.min())

0


In [58]:
#method 28 standard deviation
a = np.array([(1,2,3),(4,5,6)])

print(np.std(a))

1.707825127659933


In [65]:
#method 29 ravel
v14= np.array([(1,3,3),(3,4,5)])
print(v14.ravel())

[1 3 3 3 4 5]


In [66]:
#method 30 repaeating
v15 = np.repeat(4, 2)
print(v14)
v16 = np.array([[1,2],[3,4]])
print(np.repeat(v16, 2))

[[1 3 3]
 [3 4 5]]
[1 1 2 2 3 3 4 4]


In [67]:
#method 31 eye
arr=np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [81]:
#method 32 diag
arr=np.diag([2,3,4,5])
arr

array([[2, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 5]])

In [82]:
#method 33 shape of array
a=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(a)
print("Shape of array=", arr.shape)

Shape of array= (3, 3)


In [84]:
#method 34 zeros

arr=np.zeros((2,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.]])

In [89]:
#method 35 random int
arr=np.random.randint(1,10,3)
arr

array([5, 9, 7])

In [90]:
#method 36 onces

arr=np.ones((2,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [91]:
#method 37 Arrange
a = np.arange(5000000)
a
%time



Wall time: 0 ns


In [94]:
#method 38 data type
v16 = np.arange(1,100,10)

x.dtype


dtype('int32')

In [95]:
#method 39 linespace
np.linspace(1,72,5)

array([ 1.  , 18.75, 36.5 , 54.25, 72.  ])

In [107]:
#method 40 tan method
a4=np.array([10,20,30,40])
np.tan(a4)

array([ 0.64836083,  2.23716094, -6.4053312 , -1.11721493])

In [108]:
#method 41 ardin method
arr5=np.array([10,20,30,40])
np.argmin(arr5)

0

In [109]:
#method 42 square root
v16=np.array([10,20,30,40])
np.sqrt(16)

4.0

In [110]:
#method 43 linespace
b = np.linspace(0,25,4)
b

array([ 0.        ,  8.33333333, 16.66666667, 25.        ])

In [111]:
#method 45
b = np.array(["a","b","c"])
b = b.size
b

3

In [112]:
#method 46
#29. converting data type of an array
a = np.array([1,2,3,4,5])
a = a.astype(str)
a

array(['1', '2', '3', '4', '5'], dtype='<U11')

In [125]:
#method 47 transpose of 2x3 to 3x2 array
a2 = np.array([1,5,3,6,5,6])
a2 = a2.reshape((6,1))
a2 = a2.T
a2

array([[1, 5, 3, 6, 5, 6]])

In [122]:
#method 48 zerp expand
x1 = np.zeros((3, 4))
y2 = np.expand_dims(x1, axis=1).shape
print(y)

(3, 1, 4)


In [121]:
#method 49 collumn stack
a = np.array((60,20,30))
b = np.array((50,50,90))
c = np.column_stack((a, b))
print(c)

[[60 50]
 [20 50]
 [30 90]]


In [120]:
#method 50 roundoff
a = np.array([4.0312000,5.600,6.5000,7.445120])
a = np.round(a)
a

array([4., 6., 6., 7.])